name: README magik

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  magik:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout generator repository
        uses: actions/checkout@v4
        with:
          path: readme-magik

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.repository_owner }}
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests
        working-directory: ./readme-magik

      - name: Generate README
        env:
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
        run: python ../readme-magik/generate_readme.py
        working-directory: ./${{ github.repository_owner }}

      - name: Commit and push changes
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE/${{ github.repository_owner }}"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          # Commit only if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "🪄 Sprinkle the README with some magik"
            git push
          else
            echo "No changes to commit"
          fi
        working-directory: ./${{ github.repository_owner }}